# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llama_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llama_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13llama_service.proto\"\x1d\n\x0bTextRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"&\n\x0cTextResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t2;\n\x0cLlamaService\x12+\n\x0cGenerateText\x12\x0c.TextRequest\x1a\r.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llama_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=23
  _globals['_TEXTREQUEST']._serialized_end=52
  _globals['_TEXTRESPONSE']._serialized_start=54
  _globals['_TEXTRESPONSE']._serialized_end=92
  _globals['_LLAMASERVICE']._serialized_start=94
  _globals['_LLAMASERVICE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
